PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE menu (id varchar(40), IdParent varchar(40), Link varchar(250), Name varchar(250), Type varchar(20), order_no Integer);
INSERT INTO "menu" VALUES('system','','','System','',0);
INSERT INTO "menu" VALUES('usermgr','system','','Users','module',4);
INSERT INTO "menu" VALUES('grouplist','usermgr','','Groups','module',42);
INSERT INTO "menu" VALUES('userlist','usermgr','','Users','module',41);
INSERT INTO "menu" VALUES('group_permission','usermgr','','Group Permission','module',43);
INSERT INTO "menu" VALUES('preferences','system','','Preferences','module',10);
INSERT INTO "menu" VALUES('language','preferences','','Language','module',101);
INSERT INTO "menu" VALUES('themes_system','preferences','','Themes','module',103);
INSERT INTO "menu" VALUES('agenda','','','Agenda','',2);
INSERT INTO "menu" VALUES('calendar','agenda','','Calendar','module',1);
INSERT INTO "menu" VALUES('address_book','agenda','','Address Book','module',2);
INSERT INTO "menu" VALUES('email_admin','','','Email','',3);
INSERT INTO "menu" VALUES('email_domains','email_admin','','Domains','module',1);
INSERT INTO "menu" VALUES('email_accounts','email_admin','','Accounts','module',2);
INSERT INTO "menu" VALUES('email_relay','email_admin','','Relay','module',3);
INSERT INTO "menu" VALUES('antispam','email_admin','','Antispam','module',5);
INSERT INTO "menu" VALUES('remote_smtp','email_admin','','Remote SMTP','module',6);
INSERT INTO "menu" VALUES('email_list','email_admin','','Email list','module',7);
INSERT INTO "menu" VALUES('email_stats','email_admin','','Email stats','module',8);
INSERT INTO "menu" VALUES('vacations','email_admin','','Vacations','module',9);
INSERT INTO "menu" VALUES('webmail','email_admin','mail','Webmail','framed',4);
INSERT INTO "menu" VALUES('addons','','','Addons','',10);
INSERT INTO "menu" VALUES('addons_availables','addons','','Addons','module',1);
INSERT INTO "menu" VALUES('fax','','','Fax','',4);
INSERT INTO "menu" VALUES('virtual_fax','fax','','Virtual Fax','module',1);
INSERT INTO "menu" VALUES('faxlist','virtual_fax','','Virtual Fax List','module',11);
INSERT INTO "menu" VALUES('faxnew','virtual_fax','','New Virtual Fax','module',12);
INSERT INTO "menu" VALUES('sendfax','virtual_fax','','Send Fax','module',13);
INSERT INTO "menu" VALUES('faxqueue','virtual_fax','','Fax Queue','module',14);
INSERT INTO "menu" VALUES('faxmaster','fax','','Fax Master','module',2);
INSERT INTO "menu" VALUES('faxclients','fax','','Fax Clients','module',3);
INSERT INTO "menu" VALUES('faxviewer','fax','','Fax Viewer','module',4);
INSERT INTO "menu" VALUES('email_template','fax','','Email Template','module',5);
INSERT INTO "menu" VALUES('sysdash','system','','Dashboard','module',1);
INSERT INTO "menu" VALUES('dashboard','sysdash','','Dashboard','module',11);
INSERT INTO "menu" VALUES('applet_admin','sysdash','','Dashboard Applet Admin','module',12);
INSERT INTO "menu" VALUES('network','system','','Network','module',3);
INSERT INTO "menu" VALUES('network_parameters','network','','Network Parameters','module',31);
INSERT INTO "menu" VALUES('dhcp_server','network','','DHCP Server','module',32);
INSERT INTO "menu" VALUES('dhcp_clientlist','network','','DHCP Client List','module',33);
INSERT INTO "menu" VALUES('dhcp_by_mac','network','','Assign IP Address to Host','module',34);
INSERT INTO "menu" VALUES('ping','network','','Ping & Tracepath','module',35);
INSERT INTO "menu" VALUES('shutdown','system','','Shutdown','module',6);
INSERT INTO "menu" VALUES('hardware_detector','system','','Hardware Detector','module',7);
INSERT INTO "menu" VALUES('updates','system','','Updates','module',8);
INSERT INTO "menu" VALUES('packages','updates','','Packages','module',82);
INSERT INTO "menu" VALUES('repositories','updates','','Repositories','module',81);
INSERT INTO "menu" VALUES('backup_restore','system','','Backup/Restore','module',9);
INSERT INTO "menu" VALUES('time_config','preferences','','Date/Time','module',102);
INSERT INTO "menu" VALUES('currency','preferences','','Currency','module',104);
INSERT INTO "menu" VALUES('my_extension','','','My Extension','',11);
INSERT INTO "menu" VALUES('myex_config','my_extension','','Settings','module',1);
INSERT INTO "menu" VALUES('pbxconfig','','','PBX','',5);
INSERT INTO "menu" VALUES('pbxadmin','pbxconfig','','PBX Configuration','module',1);
INSERT INTO "menu" VALUES('control_panel','pbxconfig','','Operator Panel','module',2);
INSERT INTO "menu" VALUES('voicemail','pbxconfig','','Voicemail','module',3);
INSERT INTO "menu" VALUES('monitoring','pbxconfig','','Calls Recordings','module',4);
INSERT INTO "menu" VALUES('endpoints','pbxconfig','','Batch Configurations','module',5);
INSERT INTO "menu" VALUES('extensions_batch','endpoints','','Batch of Extensions','module',53);
INSERT INTO "menu" VALUES('conference','pbxconfig','','Conference','module',6);
INSERT INTO "menu" VALUES('tools','pbxconfig','','Tools','module',8);
INSERT INTO "menu" VALUES('asterisk_cli','tools','','Asterisk-Cli','module',81);
INSERT INTO "menu" VALUES('file_editor','tools','','Asterisk File Editor','module',82);
INSERT INTO "menu" VALUES('text_to_wav','tools','','Text to Wav','module',83);
INSERT INTO "menu" VALUES('festival','tools','','Festival','module',84);
INSERT INTO "menu" VALUES('recordings','tools','','Recordings','module',85);
INSERT INTO "menu" VALUES('security','','','Security','',12);
INSERT INTO "menu" VALUES('sec_firewall','security','','Firewall','module',1);
INSERT INTO "menu" VALUES('sec_rules','sec_firewall','','Firewall Rules','module',1);
INSERT INTO "menu" VALUES('sec_ports','sec_firewall','','Define Ports','module',2);
INSERT INTO "menu" VALUES('sec_portknock_if','sec_firewall','','Port Knocking Interfaces','module',10);
INSERT INTO "menu" VALUES('sec_portknock_users','sec_firewall','','Port Knocking Users','module',11);
INSERT INTO "menu" VALUES('fail2ban','security','','Fail2Ban','module',2);
INSERT INTO "menu" VALUES('sec_fb_admin','fail2ban','','Admin','module',1);
INSERT INTO "menu" VALUES('sec_fb_banned','fail2ban','','Banned IPs','module',2);
INSERT INTO "menu" VALUES('sec_accessaudit','security','','Audit','module',3);
INSERT INTO "menu" VALUES('sec_weak_keys','security','','Weak Keys','module',4);
INSERT INTO "menu" VALUES('sec_advanced_settings','security','','Advanced Settings','module',5);
INSERT INTO "menu" VALUES('sec_letsencrypt','security','','HTTPS Certificate (Let''s Encrypt)','module',6);
INSERT INTO "menu" VALUES('addons_license','addons','','License Manager','module',11);
INSERT INTO "menu" VALUES('extras','','','Extras','',9);
INSERT INTO "menu" VALUES('downloads','extras','','Downloads','module',3);
INSERT INTO "menu" VALUES('sphones','downloads','','Softphones','module',31);
INSERT INTO "menu" VALUES('faxutils','downloads','','Fax Utilities','module',32);
INSERT INTO "menu" VALUES('instantmessaging','downloads','','Instant Messaging','module',33);
INSERT INTO "menu" VALUES('meet','extras','','Issabel Meet','module',1);
INSERT INTO "menu" VALUES('reports','','','Reports','',8);
INSERT INTO "menu" VALUES('cdrreport','reports','','CDR Report','module',1);
INSERT INTO "menu" VALUES('channelusage','reports','','Channels Usage','module',2);
INSERT INTO "menu" VALUES('billing','reports','','Billing','module',3);
INSERT INTO "menu" VALUES('billing_rates','billing','','Rates','module',31);
INSERT INTO "menu" VALUES('billing_report','billing','','Billing Report','module',32);
INSERT INTO "menu" VALUES('dest_distribution','billing','','Destination Distribution','module',33);
INSERT INTO "menu" VALUES('billing_setup','billing','','Billing Setup','module',34);
INSERT INTO "menu" VALUES('asterisk_log','reports','','Asterisk Logs','module',4);
INSERT INTO "menu" VALUES('graphic_report','reports','','Graphic Report','module',5);
INSERT INTO "menu" VALUES('summary_by_extension','reports','','Summary','module',6);
INSERT INTO "menu" VALUES('missed_calls','reports','','Missed Calls','module',7);
INSERT INTO "menu" VALUES('webconsole','system','/console/','Web Console','framed',9);
INSERT INTO "menu" VALUES('endpoint_configurator','pbxconfig','','Endpoint Configurator','module',51);
INSERT INTO "menu" VALUES('call_center','','','Call Center','',9);
INSERT INTO "menu" VALUES('agent_console','call_center','','Agent Console','module',1);
INSERT INTO "menu" VALUES('outgoing_calls','call_center','','Outgoing Calls','module',2);
INSERT INTO "menu" VALUES('campaign_out','outgoing_calls','','Campaigns','module',21);
INSERT INTO "menu" VALUES('dont_call_list','outgoing_calls','','Do not Call List','module',22);
INSERT INTO "menu" VALUES('external_url','outgoing_calls','','External URLs','module',23);
INSERT INTO "menu" VALUES('ingoing_calls','call_center','','Ingoing Calls','module',3);
INSERT INTO "menu" VALUES('queues','ingoing_calls','','Queues','module',31);
INSERT INTO "menu" VALUES('client','ingoing_calls','','Clients','module',32);
INSERT INTO "menu" VALUES('campaign_in','ingoing_calls','','Ingoing Campaigns','module',33);
INSERT INTO "menu" VALUES('agentoptions','call_center','','Agent Options','module',4);
INSERT INTO "menu" VALUES('agents','agentoptions','','Agents','module',4);
INSERT INTO "menu" VALUES('eccp_users','agentoptions','','ECCP Users','module',4);
INSERT INTO "menu" VALUES('cb_extensions','agentoptions','','Callback Extensions','module',4);
INSERT INTO "menu" VALUES('break_administrator','call_center','','Breaks','module',5);
INSERT INTO "menu" VALUES('forms','call_center','','Forms','module',6);
INSERT INTO "menu" VALUES('form_designer','forms','','Form Designer','module',61);
INSERT INTO "menu" VALUES('form_list','forms','','Form Preview','module',62);
INSERT INTO "menu" VALUES('reports_ingoing_call','call_center','','Reports','module',7);
INSERT INTO "menu" VALUES('reports_break','reports_ingoing_call','','Reports Break','module',71);
INSERT INTO "menu" VALUES('calls_detail','reports_ingoing_call','','Calls Detail','module',72);
INSERT INTO "menu" VALUES('calls_per_hour','reports_ingoing_call','','Calls per hour','module',73);
INSERT INTO "menu" VALUES('calls_per_agent','reports_ingoing_call','','Calls per Agent','module',74);
INSERT INTO "menu" VALUES('hold_time','reports_ingoing_call','','Hold Time','module',75);
INSERT INTO "menu" VALUES('login_logout','reports_ingoing_call','','Login Logout','module',76);
INSERT INTO "menu" VALUES('ingoings_calls_success','reports_ingoing_call','','Ingoing Calls Success','module',77);
INSERT INTO "menu" VALUES('graphic_calls','reports_ingoing_call','','Graphic Calls per hour','module',78);
INSERT INTO "menu" VALUES('rep_agent_information','reports_ingoing_call','','Agent Information','module',710);
INSERT INTO "menu" VALUES('rep_agents_monitoring','reports_ingoing_call','','Agents Monitoring','module',711);
INSERT INTO "menu" VALUES('rep_trunks_used_per_hour','reports_ingoing_call','','Trunks used per hour','module',712);
INSERT INTO "menu" VALUES('rep_incoming_calls_monitoring','reports_ingoing_call','','Incoming calls monitoring','module',714);
INSERT INTO "menu" VALUES('campaign_monitoring','reports_ingoing_call','','Campaign monitoring','module',715);
INSERT INTO "menu" VALUES('callcenter_config','call_center','','Configuration','module',8);
INSERT INTO "menu" VALUES('packet_capture','network','','Packet Capture','module',38);
INSERT INTO "menu" VALUES('upnpc','network','','uPnP Control','module',39);
INSERT INTO "menu" VALUES('theme_designer','system','','Theme Designer','module',11);
INSERT INTO "menu" VALUES('sec_2fa','security','','Two Factor Authentication','module',1);
INSERT INTO "menu" VALUES('notificacion_eventos','','','Notificación de Eventos','',10);
INSERT INTO "menu" VALUES('configuracion_general','notificacion_eventos','','Configuración General','module',1);
INSERT INTO "menu" VALUES('reportes','notificacion_eventos','','Reportes','module',2);
INSERT INTO "menu" VALUES('logs','notificacion_eventos','','Logs','module',3);
INSERT INTO "menu" VALUES('auditorias','notificacion_eventos','','Auditorias','module',4);
INSERT INTO "menu" VALUES('configuracion_ivrecs','notificacion_eventos','','Configuración de IVR ECS','module',5);
INSERT INTO "menu" VALUES('configuracion_general_module','system','','Conexiones a Bases de Datos','module',11);
COMMIT;
